
CREATE TABLE TB_BASE_DEPT (
    ID bigint  IDENTITY(1,1)    NOT NULL,
    DEPT_CODE varchar(4) NOT NULL,
    DEPT_NAME varchar(100) NOT NULL,
    DEPT_TYPE bigint  NOT NULL,
    ST_ID bigint  NOT NULL,
    ENABLE varchar(1) NULL,
    PRIMARY KEY(id)
 );

CREATE TABLE TB_BASE_GROUP (
    ID bigint  IDENTITY(1,1) NOT NULL,
    DP_ID bigint  NOT NULL,
    GROUP_NAME varchar(64) NOT NULL,
    GROUP_TYPE bigint  NOT NULL,
    PRIMARY KEY(id)
 );

CREATE TABLE TB_BASE_PARA_DTL (
    ID bigint IDENTITY(1,1) NOT NULL,
    PARA_TYPE varchar(4) NOT NULL,
    PARA_CODE varchar(6) NOT NULL,
    CODE_DESC varchar(40) NOT NULL,
    SORTBY varchar(4) NULL,
    UPD_DATE datetime  NULL,
    EMP_NAME varchar(20) NOT NULL,
    PRIMARY KEY(id)
 );

CREATE TABLE TB_BASE_PERSON (
    ID bigint IDENTITY(1,1) NOT NULL,
    GROUP_ID bigint NULL,
    DP_ID bigint NULL,
    EMP_CODE varchar(10) NULL,
    LOGIN_NAME varchar(60) NULL,
    LOGIN_PASSWORD varchar(60) NULL,
    EMP_NAME varchar(20) NULL,
    POST bigint  NULL,
    SEX varchar(1)  NULL,
    MOBILE varchar(20) NULL,
    OFFICE_TEL varchar(40) NULL,
    OFFICE_PASSWORD varchar(40) NULL,
    EMAIL varchar(100) NULL,
    DORM varchar(100) NULL,
    IDTY_CARD varchar(18) NULL,
    UPDDATE datetime  NULL,
    BIRTHDAY datetime  NULL,
    PRIMARY KEY(id)
 );

CREATE TABLE TB_BASE_PERSON_BASE_COL_REF (
    ID bigint  IDENTITY(1,1) NOT NULL,
    PERSON_ID bigint  NOT NULL,
    MODEL_NAME varchar  (50) NOT NULL,
    MODEL_PROPERTIES varchar  (512) NOT NULL,
    PRIMARY KEY(id)
 );

/*---------TB_BASE_DEPT-----------*/
 Insert into TB_BASE_DEPT (ID,DEPT_CODE,DEPT_NAME,DEPT_TYPE,ST_ID)
       values ( 1, '17', '∞Ïπ´ “', 41, 1 );
 Insert into TB_BASE_DEPT (ID,DEPT_CODE,DEPT_NAME,DEPT_TYPE,ST_ID)
       values ( 2, '4000', 'º◊≤ø√≈', 42, 1 );
 Insert into TB_BASE_DEPT (ID,DEPT_CODE,DEPT_NAME,DEPT_TYPE,ST_ID)
       values ( 3, '41', '““≤ø√≈', 43, 1 );
 Insert into TB_BASE_DEPT (ID,DEPT_CODE,DEPT_NAME,DEPT_TYPE,ST_ID)
       values ( 4, '15', '±˚≤ø√≈', 38, 1 );
 Insert into TB_BASE_DEPT (ID,DEPT_CODE,DEPT_NAME,DEPT_TYPE,ST_ID)
       values ( 5, '08', '∂°≤ø√≈', 40, 1 );
 Insert into TB_BASE_DEPT (ID,DEPT_CODE,DEPT_NAME,DEPT_TYPE,ST_ID)
       values ( 6, '01', '¡Ïµº≤„', 39, 1 );
/*---------TB_BASE_GROUP-----------*/
 Insert into TB_BASE_GROUP (ID,DP_ID,GROUP_NAME,GROUP_TYPE)
       values ( 1, 2, '“ª∞‡', 11 );
 Insert into TB_BASE_GROUP (ID,DP_ID,GROUP_NAME,GROUP_TYPE)
       values ( 2, 2, '∂˛∞‡', 11 );
 Insert into TB_BASE_GROUP (ID,DP_ID,GROUP_NAME,GROUP_TYPE)
       values ( 3, 2, '»˝∞‡', 11 );
 Insert into TB_BASE_GROUP (ID,DP_ID,GROUP_NAME,GROUP_TYPE)
       values ( 4, 2, 'Àƒ∞‡', 11 );
 Insert into TB_BASE_GROUP (ID,DP_ID,GROUP_NAME,GROUP_TYPE)
       values ( 5, 2, 'ŒÂ∞‡', 11 );
 Insert into TB_BASE_GROUP (ID,DP_ID,GROUP_NAME,GROUP_TYPE)
       values ( 6, 2, '¡˘∞‡', 11 );
 Insert into TB_BASE_GROUP (ID,DP_ID,GROUP_NAME,GROUP_TYPE)
       values ( 7, 3, '“ª∞‡', 11 );
 Insert into TB_BASE_GROUP (ID,DP_ID,GROUP_NAME,GROUP_TYPE)
       values ( 8, 3, '∂˛∞‡', 11 );
 Insert into TB_BASE_GROUP (ID,DP_ID,GROUP_NAME,GROUP_TYPE)
       values ( 9, 3, '»˝∞‡', 11 );
 Insert into TB_BASE_GROUP (ID,DP_ID,GROUP_NAME,GROUP_TYPE)
       values ( 10, 3, 'Àƒ∞‡', 11 );
 Insert into TB_BASE_GROUP (ID,DP_ID,GROUP_NAME,GROUP_TYPE)
       values ( 11, 3, 'ŒÂ∞‡', 11 );
 Insert into TB_BASE_GROUP (ID,DP_ID,GROUP_NAME,GROUP_TYPE)
       values ( 12, 3, '¡˘∞‡', 11 );
 Insert into TB_BASE_GROUP (ID,DP_ID,GROUP_NAME,GROUP_TYPE)
       values ( 13, 4, '“ª∞‡', 11 );
 Insert into TB_BASE_GROUP (ID,DP_ID,GROUP_NAME,GROUP_TYPE)
       values ( 14, 4, '∂˛∞‡', 11 );
 Insert into TB_BASE_GROUP (ID,DP_ID,GROUP_NAME,GROUP_TYPE)
       values ( 15, 4, '»˝∞‡', 11 );
 Insert into TB_BASE_GROUP (ID,DP_ID,GROUP_NAME,GROUP_TYPE)
       values ( 16, 4, 'Àƒ∞‡', 11 );

/*---------TB_BASE_PERSON-----------*/
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 115, 1, 2, '0000', 'admin', 'admin', 'π‹¿Ì‘±', NULL, 0, '123123', NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 117, 9, 3, '00088', NULL, NULL, '≤‹≤Ÿ', NULL, 1, '1111', NULL, NULL, NULL, NULL, NULL, '2012-07-27', '2012-08-01' );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 4, 9, 3, '80', 'yutao', 'yutao', '’≈¡…', 14, 1, '1111', NULL, NULL, NULL, NULL, NULL, '2012-07-27', '2012-08-01' );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 12, 16, 4, '38', NULL, NULL, 'œƒ∫Óê™', 16, 1, '12312', NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 13, 6, 2, '40', 'yanglin', 'yanglin', 'π˘ºŒ', 14, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 14, 16, 4, '41', 'liwei', 'liwei', '¡ı±∏', 16, 1, '12312', NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 15, 16, 4, '43', NULL, NULL, '÷Ó∏¡¡', 16, 1, '12312', NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 18, 3, 2, '47', NULL, NULL, 'πÿ”', 16, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 19, 6, 2, '48', NULL, NULL, '’≈∑…', 16, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 20, 5, 2, '49', NULL, NULL, '’‘‘∆', 16, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 21, 2, 2, '56', 'liguoqi', 'liguoqi', '¬Ì≥¨', 14, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 22, 2, 2, '67', NULL, NULL, 'ª∆‘¬”¢', 16, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 23, 5, 2, '69', NULL, NULL, 'ÀÔ»®', 16, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 24, 3, 2, '64', NULL, NULL, '∏ ƒ˛', 16, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 25, 6, 2, '77', NULL, NULL, '÷‹Ë§', 16, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 26, 3, 2, '71', NULL, NULL, '¬¿√…', 16, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 27, 2, 2, '115', NULL, NULL, '¬Ω—∑', 16, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 28, 1, 2, '52', NULL, NULL, 'ÀÔ…–œ„', 16, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 29, 4, 2, '108', 'zhangrenming', '1', 'ª∆∏«', 16, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 30, NULL, 4, '15', NULL, NULL, '¥Û««', 1, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 31, NULL, 4, '16', NULL, NULL, '¬¿≤º', 2, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 32, NULL, 3, '21', NULL, NULL, 'ª™Ÿ¢', 4, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 33, NULL, 3, '19', NULL, NULL, 'ıı≤ı', 2, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 34, NULL, 3, '13', NULL, NULL, '≤‹» ', 2, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 35, 11, 3, '42', NULL, NULL, 'œƒ∫Ó‘®', 14, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 36, 7, 3, '35', NULL, NULL, 'Œ∫—”', 14, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 37, 15, 4, '72', NULL, NULL, 'ª∆÷“', 14, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 38, 16, 4, '63', NULL, NULL, '÷‹Ã©', 14, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 39, 16, 4, '60', NULL, NULL, '–°««', 16, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 40, 16, 4, '66', NULL, NULL, '”⁄º™', 16, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 41, 15, 4, '73', NULL, NULL, '’≈Ω«', 16, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 42, 10, 3, '55', NULL, NULL, 'πÿ”', 14, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 43, 9, 3, '59', NULL, NULL, '¬¿√…', 14, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 44, 8, 3, '88', NULL, NULL, '‹˜è™', 14, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 45, 14, 3, '65', NULL, NULL, 'µ‰Œ§', 16, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 46, 14, 3, '91', NULL, NULL, '÷Ó∏¡¡', 14, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 47, 10, 3, '79', NULL, NULL, '≈”Õ≥', 16, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 48, 9, 3, '62', NULL, NULL, 'Ã´ ∑¥»', 16, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 49, 8, 3, '81', NULL, NULL, '‘¨…‹', 16, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 50, 7, 3, '34', NULL, NULL, '≈”µ¬', 16, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 51, NULL, 5, '17', 'jiangbinghang', 'jiangbinghang', '—’¡º', 2, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 87, NULL, 2, NULL, NULL, NULL, 'Œƒ≥Û', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 53, 16, 4, '01', NULL, NULL, '÷‹Ë§', 14, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 54, 11, 3, '02', NULL, NULL, '–ÏªŒ', 16, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 55, 14, 3, '03', NULL, NULL, '≤‹ÿß', 16, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 56, 11, 3, '04', NULL, NULL, '√œªÒ', 16, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 57, 7, 3, '05', NULL, NULL, '◊£»⁄', 16, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 58, 16, 4, '06', 'wangyu', '1', '¬≥À‡', 16, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 59, 16, 4, '07', NULL, NULL, 'ÀÔº·', 14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 60, 1, 6, '08', 'liujianguo', 'liujianguo', '∂≠◊ø', 12, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 61, 1, 6, '09', 'zhangyueyue', 'zhangyueyue', 'º÷⁄º', 13, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 62, 1, 2, '135', 'xuming', 'xuming', '’≈‡A', 14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
 Insert into TB_BASE_PERSON (ID,GROUP_ID,DP_ID,EMP_CODE,LOGIN_NAME,LOGIN_PASSWORD,EMP_NAME,POST,SEX,MOBILE,OFFICE_TEL,OFFICE_PASSWORD,EMAIL,DORM,IDTY_CARD,UPDDATE,BIRTHDAY)
       values ( 63, 1, 2, '136', 'zhangpeng1', 'zhangpeng1', '”⁄Ω˚', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL );
/*---------TB_BASE_PERSON_BASE_COL_REF-----------*/
 Insert into TB_BASE_PERSON_BASE_COL_REF (ID,PERSON_ID,MODEL_NAME,MODEL_PROPERTIES)
       values ( 1, 115, 'Person', 'name,dept.name,group.name,updDate' );
